### Training model with Iris dataset


In [17]:
import numpy as np
import tensorflow as tf

print(tf.__file__ )

c:\program files\python\python36\lib\site-packages\tensorflow\__init__.py


In [2]:
# Tensorflow already have Iris dataset we can use to train our model.
# Set contains 2 list:
#     1) Length and width data for petal and sepal of each flower sample
#     2) 3 dimensional vector of species types. 
#        Each specy is represented by 0, 1, 2 to be setosa, versicolor and virginica respectively.
iris_set = tf.contrib.learn.datasets.load_iris()

# print(iris_train.data)
# print(iris_train.target)


In [3]:
# Simple example of how to shuffle elemnts in 2 arrays of the same length  
# and maintain shuffle order for both.
# Adopted from https://stackoverflow.com/questions/4601373/better-way-to-shuffle-two-numpy-arrays-in-unison

arr1 = [1, 2, 3, 4, 5]
arr2 = [11, 12, 13, 14, 15]

arr1 =  np.array(arr1)
arr2 =  np.array(arr2)
# list of indexes equal to the length of target array
randomize = np.arange(len(arr1))
print(randomize)
# shuffle it
np.random.shuffle(randomize)

# set a new index order for both arrays
arr1 = arr1[randomize]
arr2 = arr2[randomize]

print(arr1)
print(arr2)

[0 1 2 3 4]
[2 1 3 5 4]
[12 11 13 15 14]


In [12]:
# Shuffle data to randomly pick train and test sets 
# to train and test model.

data = iris_set.data
target = iris_set.target
 
randomize = np.arange(len(data))
np.random.shuffle(randomize)
data = data[randomize]
target = target[randomize]

inds = np.random.permutation(len(data))
train_inds, test_inds = np.array_split(inds, 2)
training_data, training_target = data[train_inds], target[train_inds]
test_data, test_target  = data[test_inds],  target[test_inds]

inds2 = np.random.permutation(len(training_data))
train_inds2, test_inds2 = np.array_split(inds2, 2)
training_data2, training_target2 = training_data[train_inds2], training_target[train_inds2]


print(len(training_data2))
# print(len(test_data))

# print(training_data)
# print(test_data)


38


In [21]:
# Code is adopted from tutorial: https://www.tensorflow.org/get_started/estimator


# Specify that all features have real-value data
feature_columns = [tf.feature_column.numeric_column("x", shape=[4])]

# Build 3 layer DNN with 10, 20, 10 units respectively.
classifier = tf.estimator.DNNClassifier(feature_columns=feature_columns,
                                      hidden_units=[10, 20, 10],
                                      n_classes=3,
                                      model_dir="./models/iris_model")
# Define the training inputs
train_input_fn = tf.estimator.inputs.numpy_input_fn(
  x={"x": np.array(training_data2)},
  y=np.array(training_target2),
  num_epochs=None,
  shuffle=True)

# Train model.
classifier.train(input_fn=train_input_fn, steps=3000)

# Define the test inputs
test_input_fn = tf.estimator.inputs.numpy_input_fn(
  x={"x": np.array(test_data)},
  y=np.array(test_target),
  num_epochs=1,
  shuffle=False)

# Evaluate accuracy.
accuracy_score = classifier.evaluate(input_fn=test_input_fn)["accuracy"]

print("\nTest Accuracy: {0:f}\n".format(accuracy_score))

# Classify new flower samples.
new_samples = np.array(
  [[6.4, 3.2, 4.5, 1.5],
   [5.8, 3.1, 5.0, 1.7],
   [4.6, 3.4, 1.4, 0.3],
   [5.9, 3.0, 5.1, 1.8]], dtype=np.float32)

predict_input_fn = tf.estimator.inputs.numpy_input_fn(
  x={"x": new_samples},
  num_epochs=1,
  shuffle=False)

predictions = list(classifier.predict(input_fn=predict_input_fn))
predicted_classes = [p["classes"] for p in predictions]

print(
  "New Samples, Class Predictions:    {}\n"
  .format(predicted_classes))

print(predicted_classes)

INFO:tensorflow:Using default config.
INFO:tensorflow:Using config: {'_model_dir': './models/iris_model', '_tf_random_seed': 1, '_save_summary_steps': 100, '_save_checkpoints_secs': 600, '_save_checkpoints_steps': None, '_session_config': None, '_keep_checkpoint_max': 5, '_keep_checkpoint_every_n_hours': 10000, '_log_step_count_steps': 100}
INFO:tensorflow:Create CheckpointSaverHook.
INFO:tensorflow:Restoring parameters from ./models/iris_model\model.ckpt-5000
INFO:tensorflow:Saving checkpoints for 5001 into ./models/iris_model\model.ckpt.
INFO:tensorflow:loss = 0.0304869, step = 5001
INFO:tensorflow:global_step/sec: 365.466
INFO:tensorflow:loss = 0.029474, step = 5101 (0.278 sec)
INFO:tensorflow:global_step/sec: 635.908
INFO:tensorflow:loss = 0.0320262, step = 5201 (0.169 sec)
INFO:tensorflow:global_step/sec: 555.097
INFO:tensorflow:loss = 0.0289238, step = 5301 (0.165 sec)
INFO:tensorflow:global_step/sec: 600.226
INFO:tensorflow:loss = 0.033098, step = 5401 (0.167 sec)
INFO:tensorflo

In [55]:
predictions = np.array(predicted_classes).astype(int)
flowers = ['setosa', 'versicolor', 'virginica']
report = []

for index, item in enumerate(predictions):
    if(item == 0):
        report.append('setosa') #flowers[0] 
    elif(item == 1):
        report.append('versicolor') #flowers[1] 
    elif(item == 2):
        report.append('virginica') #flowers[2]  
print(report)

['versicolor', 'virginica', 'setosa', 'virginica']
